permissionset 72094 "DOPSWHS-ADMIN"
{
    Assignable = true;
    Caption = 'Advanced WMS Admin';

    Permissions =
        tabledata "DOPSWHS Setup" = RIMD,
        tabledata "DOPSWHS Device Configuration" = RIMD,
        tabledata "DOPSWHS Device Menu" = RIMD,
        tabledata "DOPSWHS Device Column" = RIMD,
        tabledata "DOPSWHS Device Registration" = RIMD,
        tabledata "DOPSWHS Barcode Rule" = RIMD,
        tabledata "DOPSWHS Barcode Symbology" = RIMD,
        tabledata "DOPSWHS Telemetry Buffer" = RIMD,
        table "DOPSWHS Setup" = X,
        table "DOPSWHS Device Configuration" = X,
        table "DOPSWHS Device Menu" = X,
        table "DOPSWHS Device Column" = X,
        table "DOPSWHS Device Registration" = X,
        table "DOPSWHS Barcode Rule" = X,
        table "DOPSWHS Barcode Symbology" = X,
        table "DOPSWHS Telemetry Buffer" = X,
        page "DOPSWHS Setup" = X,
        page "DOPSWHS Device Config Card" = X,
        page "DOPSWHS Device Config List" = X,
        page "DOPSWHS Device Menu List" = X,
        page "DOPSWHS Device Column List" = X,
        page "DOPSWHS Device Registration List" = X,
        page "DOPSWHS Barcode Rule List" = X,
        page "DOPSWHS Symbology List" = X,
        page "DOPSWHS LP Factbox Item" = X,
        page "DOPSWHS LP Factbox Bin" = X,
        page "DOPSWHS Item API" = X,
        page "DOPSWHS Bin API" = X,
        page "DOPSWHS Device API" = X,
        page "DOPSWHS Barcode Parse API" = X,
        codeunit "DOPSWHS Setup Wizard" = X,
        codeunit "DOPSWHS Barcode Parser" = X,
        codeunit "DOPSWHS GS1 AI Parser" = X,
        codeunit "DOPSWHS Device Auth" = X,
        codeunit "DOPSWHS Telemetry" = X,
        codeunit "DOPSWHS Install" = X,
        codeunit "DOPSWHS Upgrade" = X,
        codeunit "DOPSWHS Permission Helper" = X;
}
