"""Convert the existing BS Group asset to the rotated monochrome MTE graphic.

Run after changing the source logo; keeps the AL literal and preview in sync.
"""
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[3]
source = root / 'android/app/src/main/res/drawable-nodpi/logo_bs_group.png'
logo = Image.open(source).convert('RGBA')
background = Image.new('RGBA', logo.size, 'white')
background.alpha_composite(logo)
logo = background.convert('L')
logo.thumbnail((180, 46), Image.Resampling.LANCZOS)
# Landscape position (38, 28); rotate clockwise onto portrait stock.
width, height = logo.size
logo = logo.transpose(Image.Transpose.ROTATE_270)
stride = (logo.width + 7) // 8
data = bytearray(stride * logo.height)
for y in range(logo.height):
    for x in range(logo.width):
        if logo.getpixel((x, y)) < 160:
            data[y * stride + x // 8] |= 0x80 >> (x % 8)
graphic = f'^FO{812-28-height},38^GFA,{len(data)},{len(data)},{stride},{data.hex().upper()}^FS'
Path(__file__).with_name('mte-bs-group-logo.zpl').write_text(graphic)
al = root / 'al/src/Print/MteZplBuilder.Codeunit.al'
code = al.read_text()
start = code.index('    local procedure CompanyLogo(): Text')
end = code.index('    // ------------------------------------------------------------------', start)
chunks = [graphic[i:i+120] for i in range(0, len(graphic), 120)]
literal = ' +\n            '.join("'" + chunk + "'" for chunk in chunks)
method = (
    '    local procedure CompanyLogo(): Text\n'
    '    begin\n'
    '        // Existing BS Group logo, monochrome and rotated for portrait stock.\n'
    '        // Generated by docs/labels/bade/generate-mte-logo.py.\n'
    f'        exit({literal});\n'
    '    end;\n\n'
)
al.write_text(code[:start] + method + code[end:])
